name: Deployment

on:
  push:
    branches:
      - LIVE
      - TEST

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer run test

      - name: rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr
          path: public/
          # Remote Pfad wird durch rrsync auf der Serverseite kontrolliert
          remote_path: /${{ steps.extract_branch.outputs.branch }}/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Notify done
        uses: cstuder/apprise-ga@master
        with:
          title: "XXX ${{ steps.extract_branch.outputs.branch }} deployed"
          message: "{{ head_commit.author.name }}: {{ head_commit.message | truncate(128) }} ({{ head_commit.id[0:7] }})"
        env:
          APPRISE_URL: ${{ secrets.APPRISE_URL }}
